# Core losses
lambda_hm: 1.0
lambda_off: 0.5
lambda_vis: 0.1

# Time-series regularization
lambda_v: 0.1
lambda_a: 0.05
lambda_rank: 0.02

# Confidence / Sharpening
lambda_sharp: 0.001
lambda_peak: 0.001

# Heatmap loss selection: one of [mse, focal, kl]
hm_type: mse
focal_gamma: 2.0
kl_tau: 1.0

# Detection accuracy threshold (pixels)
acc_threshold_px: 8.0
