# ITF tennis court specification for 15-keypoint annotator
# 座標系
#  - 原点は近側ベースライン中央
#  - +y は遠側方向, y=0 は近側ベースライン, y=L は遠側ベースライン
#  - +x は右, -x は左（センターラインを 0）
# 単位: メートル

schema: court_spec/v1
name: tennis_itf
units:
  length: m
  angle: deg

reference:
  standard: ITF Rules of Tennis
  note: Dimensions rounded to millimeter precision where applicable

dimensions:
  length_m: 23.770 # L
  doubles_width_m: 10.973 # Wd
  singles_width_m: 8.230 # Ws
  net_center_y_m: 11.885 # L/2
  service_line_offset_m: 6.400

# キーポイント名称（実装の KEYPOINT_NAMES と完全一致する順序）
names:
  - far_doubles_corner_left
  - far_doubles_corner_right
  - near_doubles_corner_left
  - near_doubles_corner_right
  - far_singles_corner_left
  - near_singles_corner_left
  - far_singles_corner_right
  - near_singles_corner_right
  - far_service_line_endpoint_left
  - far_service_line_endpoint_right
  - near_service_line_endpoint_left
  - near_service_line_endpoint_right
  - far_service_T
  - near_service_T
  - net_center

# スケルトン（エッジのペア）。描画および可視化で使用。
# 実装の SKELETON と一致
skeleton:
  - [0, 1] # outer doubles top
  - [2, 3] # outer doubles bottom
  - [0, 2] # outer doubles left
  - [1, 3] # outer doubles right
  - [4, 6] # singles top
  - [5, 7] # singles bottom
  - [8, 9] # far service line
  - [10, 11] # near service line
  - [12, 13] # service T spine
  - [12, 14] # far T to net center
  - [13, 14] # near T to net center
  - [0, 4] # bridge far left
  - [1, 6] # bridge far right
  - [2, 5] # bridge near left
  - [3, 7] # bridge near right

# テンプレート座標（メートル, names の順序と 1 対 1）
# x 座標は幅の半分、y はコート長に沿って定義
# 定数:
#   x_dl = -Wd/2 = -5.4865
#   x_dr =  Wd/2 =  5.4865
#   x_sl = -Ws/2 = -4.1150
#   x_sr =  Ws/2 =  4.1150
#   y_net = L/2  = 11.885
#   y_svc_near = y_net - 6.400 =  5.485
#   y_svc_far  = y_net + 6.400 = 18.285
template_xy:
  - [-5.4865, 23.770] # 0 far_doubles_corner_left
  - [5.4865, 23.770] # 1 far_doubles_corner_right
  - [-5.4865, 0.000] # 2 near_doubles_corner_left
  - [5.4865, 0.000] # 3 near_doubles_corner_right
  - [-4.1150, 23.770] # 4 far_singles_corner_left
  - [-4.1150, 0.000] # 5 near_singles_corner_left
  - [4.1150, 23.770] # 6 far_singles_corner_right
  - [4.1150, 0.000] # 7 near_singles_corner_right
  - [-4.1150, 18.285] # 8 far_service_line_endpoint_left
  - [4.1150, 18.285] # 9 far_service_line_endpoint_right
  - [-4.1150, 5.485] # 10 near_service_line_endpoint_left
  - [4.1150, 5.485] # 11 near_service_line_endpoint_right
  - [0.0000, 18.285] # 12 far_service_T
  - [0.0000, 5.485] # 13 near_service_T
  - [0.0000, 11.885] # 14 net_center

# 検証ルール（ローダ側参照用の補助情報。任意）
validation:
  expected_keypoints: 15
  index_range: [0, 14]
  skeleton_index_must_be_in_range: true
  names_length_must_match_template: true
