frames_in: 3
frames_out: 1
out_scales: [0]

MODEL:
  EXTRA:
    STEM:
      INPLANES: 64
      STRIDES: [1, 1]
    STEM3D:
      KERNELS_D: [3, 1] # conv1=3, conv2=1
      STRIDES_D: [1, 1]
      AGG: mean
    STAGE1:
      NUM_MODULES: 1
      NUM_BRANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS: [1]
      NUM_CHANNELS: [32]
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS: [2, 2]
      NUM_CHANNELS: [16, 32]
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 1
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS: [2, 2, 2]
      NUM_CHANNELS: [16, 32, 64]
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 1
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS: [2, 2, 2, 2]
      NUM_CHANNELS: [16, 32, 64, 128]
      FUSE_METHOD: SUM
    DECONV:
      NUM_DECONVS: 0
      KERNEL_SIZE: []
      NUM_BASIC_BLOCKS: 2
    FINAL_CONV_KERNEL: 1
    OUT_CHANNELS_PER_SCALE: [1, 1, 1, 1]
    PRETRAINED_LAYERS: ["*"]
