frames_in: 3
frames_out: 1
out_scales: [0]

MODEL:
  EXTRA:
    STEM:
      STRIDES: [2, 2]
      INPLANES: 64
    STEM3D:
      KERNEL_D: 3
      STRIDES_D: [1, 1]
      AGG: mean
    STAGE1:
      NUM_MODULES: 1
      NUM_BRANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS: [4]
      NUM_CHANNELS: [64]
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS: [4, 4]
      NUM_CHANNELS: [48, 96]
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS: [4, 4, 4]
      NUM_CHANNELS: [48, 96, 192]
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS: [4, 4, 4, 4]
      NUM_CHANNELS: [48, 96, 192, 384]
      FUSE_METHOD: SUM
    DECONV:
      NUM_DECONVS: 1
      KERNEL_SIZE: [4]
    FINAL_CONV_KERNEL: 1
    OUT_CHANNELS_PER_SCALE: [1, 1, 1, 1]
    PRETRAINED_LAYERS: ["*"]
