model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "${hydra:runtime.output_dir}/checkpoints"
  filename: "epoch={epoch}-val_loss={val/loss:.4f}"
  monitor: "val/loss"
  mode: "min"
  save_top_k: 3
  save_last: true

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar

custom:
  _target_: development.core.callbacks.plaggable_logger.HeatmapLoggerPluggable
  max_samples: 2
  every_n_epochs: 1
  take_first_batch_only: true
  render_fn:
    _target_: development.court_pose.dino_fpn_v2.callbacks.renderers.build_court_heatmap_renderer
    upsample_to: 448
    overlay_alpha: 0.55
    include_inputs: true
    input_key: images
    pred_key: pred_heatmaps
    gt_key: target_heatmaps
