model:
  vit_name: vit_base_patch16_224.augreg_in21k
  pretrained: true
  decoder_channels:
    - 512
    - 256
    - 128
    - 64
  heatmap_channels: 15
  output_size:
    - 224
    - 224
dataset:
  img_dir: data/processed/court/images/
  annotation_file: data/processed/court/annotation.json
  img_size:
    - 224
    - 224
  heatmap_size:
    - 224
    - 224
  heatmap_sigma: 2.0
  batch_size: 32
  num_workers: 8
  train_ratio: 0.8
  val_ratio: 0.1
  pin_memory: true
  persistent_workers: true
training:
  max_epochs: 100
  lr: 0.0001
  weight_decay: 1.0e-05
  precision: 16-mixed
  accelerator: gpu
  devices: 1
callbacks:
  checkpoint:
    monitor: val/PCK@0.05
    mode: max
    save_top_k: 3
  early_stopping:
    monitor: val/PCK@0.05
    mode: max
    patience: 10
  heatmap_logger:
    num_samples: 3
evaluation:
  pck_threshold: 0.05
