# filename: development/court_pose/01_vit_heatmap/configs/vit_heatmap_v1.yml
model:
  vit_name: "vit_base_patch16_224.augreg_in21k" # 事前学習済みモデルをより具体的に指定
  pretrained: true
  decoder_channels: [512, 256, 128, 64] # 段階的なアップサンプリング
  heatmap_channels: 15
  output_size: [224, 224] # ViT(224)の出力に合わせる (224 / 16 * 4)

data:
  img_dir: "data/processed/court/images/"
  annotation_file: "data/processed/court/annotation.json"
  img_size: [224, 224]
  heatmap_size: [224, 224]
  heatmap_sigma: 2.0
  batch_size: 32
  num_workers: 8

training:
  max_epochs: 100
  lr: 1e-4
  weight_decay: 1e-5
  precision: 16-mixed # より一般的な指定方法
  accelerator: gpu
  devices: 1

callbacks:
  checkpoint:
    monitor: "val/PCK@0.05" # 監視する指標を具体的に
    mode: max
    save_top_k: 3
  early_stopping:
    monitor: "val/PCK@0.05"
    mode: max
    patience: 10

# PCK評価用の設定
evaluation:
  pck_threshold: 0.05