visualization:
  num_samples: 4
  score_threshold: 0.5

model_checkpoint:
  dirpath: "${hydra:runtime.output_dir}/checkpoints"
  filename: "epoch={epoch}-val-loss={val-loss:.3f}"
  monitor: "val-loss"
  mode: "min"
  save_top_k: 3
  save_last: True

lr_monitor:
  logging_interval: "step"

early_stopping:
  monitor: "val-loss"
  patience: 5
  mode: "min"
