model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: "${hydra:runtime.output_dir}/checkpoints"
  filename: "epoch={epoch}-val-loss={val-loss:.3f}"
  monitor: "val-loss"
  mode: "min"
  save_top_k: 3
  save_last: True
